services:
  - docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - docker build -t $DOCKER_REPO:2.4.5 2.4.5
  - docker tag $DOCKER_REPO:2.4.5 $DOCKER_REPO:2.4.5
  - docker push $DOCKER_REPO

  - docker build -t $DOCKER_REPO:2.5.0 2.5.0
  - docker tag $DOCKER_REPO:2.5.0 $DOCKER_REPO:2.5.0
  - docker push $DOCKER_REPO

  - docker build -t $DOCKER_REPO:3.2.8 3.2.8
  - docker tag $DOCKER_REPO:3.2.8 $DOCKER_REPO:3.2.8
  - docker push $DOCKER_REPO

  - docker build -t $DOCKER_REPO:3.3.0 3.3.0
  - docker tag $DOCKER_REPO:3.3.0 $DOCKER_REPO:3.3.0
  - docker push $DOCKER_REPO

  - docker build -t $DOCKER_REPO:3.3.6 3.3.6
  - docker tag $DOCKER_REPO:3.3.6 $DOCKER_REPO:3.3.6
  - docker push $DOCKER_REPO
