services:
  - docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - docker build -t $DOCKER_REPO:$TRAVIS_BUILD_NUMBER 2.4.5
  - docker tag $DOCKER_REPO:$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO
