services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty

language: java

jdk:
  - oraclejdk8

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

jobs:
  include:
    - stage: 2.4.4
      script:
        - docker build -t $DOCKER_REPO:2.4.4 2.4.4
        - docker tag $DOCKER_REPO:2.4.4 $DOCKER_REPO:2.4.4
        - docker push $DOCKER_REPO
    - stage: 2.4.5
      script:
        - docker build -t $DOCKER_REPO:2.4.5 2.4.5
        - docker tag $DOCKER_REPO:2.4.5 $DOCKER_REPO:2.4.5
        - docker push $DOCKER_REPO
    - stage: 2.5.0
      script:
        - docker build -t $DOCKER_REPO:2.5.0 2.5.0
        - docker tag $DOCKER_REPO:2.5.0 $DOCKER_REPO:2.5.0
        - docker push $DOCKER_REPO
    - stage: 3.2.8
      script:
        - docker build -t $DOCKER_REPO:3.2.8 3.2.8
        - docker tag $DOCKER_REPO:3.2.8 $DOCKER_REPO:3.2.8
        - docker push $DOCKER_REPO
    - stage: 3.3.0
      script:
        - docker build -t $DOCKER_REPO:3.3.0 3.3.0
        - docker tag $DOCKER_REPO:3.3.0 $DOCKER_REPO:3.3.0
        - docker push $DOCKER_REPO
    - stage: 3.3.6
      script:
        - docker build -t $DOCKER_REPO:3.3.6 3.3.6
        - docker tag $DOCKER_REPO:3.3.6 $DOCKER_REPO:3.3.6
        - docker push $DOCKER_REPO
    - stage: latest
      script:
        - docker build -t $DOCKER_REPO:latest 3.3.6
        - docker tag $DOCKER_REPO:latest $DOCKER_REPO:latest
        - docker push $DOCKER_REPO
